git-debimport ipsec-tools_0.8.0-14.debian.tar.gz

diff --git a/debian/racoon.init b/debian/racoon.init
--- a/debian/racoon.init
+++ b/debian/racoon.init
@@ -11,8 +11,6 @@
 # Short-Description: start the ipsec key exchange server 
 ### END INIT INFO
 #
-# netscript	script to fire up netscript network configuration system
-#
 #		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
 #		Modified for Debian GNU/Linux
 #		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
@@ -20,13 +18,11 @@
 #		by Matthew Grant <grantma@anathoth.gen.nz>
 #
 
-set -e
-
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 TOOL=/usr/sbin/racoon-tool
 DAEMON=/usr/sbin/racoon
 NAME=racoon
-DESC="racoon"
+DESC="IKE (ISAKMP/Oakley) server"
 DEF_CFG="/etc/default/racoon"
 PID_FILE="/var/run/racoon.pid"
 PROC_FILE="/proc/net/pfkey"
@@ -54,12 +50,44 @@ check_kernel () {
 	return 0
 }
 
-if ! check_kernel ; then
+if [ "$(uname -s)" = "Linux" ] && ! check_kernel ; then
         echo "racoon - IKE keying daemon will not be started as $PROC_FILE is not" 1>&2
         echo "         available or a suitable 2.6 (or 2.4 with IPSEC backport)" 1>&2
-        echo "         kernel with af_key.[k]o module is not installed." 1>&2
+        echo "         kernel with af_key.[k]o module installed." 1>&2
 	exit 0
 fi
+
+if [ "$(uname -s)" = "GNU/kFreeBSD" ]; then
+	result=0
+	setkey -DP >/dev/null || result=$?
+	if [ $result -ne 0 ]; then
+		echo "racoon - IKE keying daemon will not be started as this kFreeBSD kernel" 1>&2
+		echo "is not compiled with support for IPsec." 1>&2
+		exit 0;
+	fi
+fi
+
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
+
+do_start () {
+        start-stop-daemon --start --quiet --pidfile $PID_FILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --exec ${DAEMON} -- ${RACOON_ARGS} \
+		|| return 2
+}
+
+do_stop () {
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID_FILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+        rm -f $PID_FILE /var/run/racoon/racoon.sock
+	return "$RETVAL"
+}
+
+
 
 case  $CONFIG_MODE in
   racoon-tool)
@@ -69,6 +97,9 @@ case  $CONFIG_MODE in
 	  start|stop|reload|force-reload|restart)
 		$TOOL $*
 		;;
+	  status)
+        	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
 	  *)
 		$TOOL $*
 		;;
@@ -76,33 +107,51 @@ case  $CONFIG_MODE in
 	;;
   *)
 	case "$1" in
-          start)
-                echo -n "Starting IKE (ISAKMP/Oakley) server: racoon"
-	        start-stop-daemon --start --quiet --exec /usr/sbin/racoon -- ${RACOON_ARGS}
-        	echo "."
+        start)
+                [ "$VERBOSE" != no ] && log_begin_msg "Starting $DESC" "$NAME"
+		do_start
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
                 ;;
          
-	  stop)
-        	echo -n "Stopping IKE (ISAKMP/Oakley) server: racoon"
-                start-stop-daemon --stop --retry 25 --quiet --oknodo \
-                    --pidfile $PID_FILE --name racoon
-                rm -f $PID_FILE /var/run/racoon/racoon.sock
-	        echo "."
-        	;;
+	stop)	
+		[ "$VERBOSE" != no ] && log_begin_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+                ;;
          
-	  reload|force-reload)
+	reload)
                 racoonctl reload-config
 	        ;;
         
+	status)
+        	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        	;;
 
-	  restart)
-                $0 stop
-                $0 start
+	restart|force-reload)
+		log_daemon_msg "Restarting $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1)
+				do_start
+                		case "$?" in
+                        		0) log_end_msg 0 ;;
+                        		1) log_end_msg 1 ;; # Old process is still running
+                        		*) log_end_msg 1 ;; # Failed to start
+                		esac
+			;;
+		*)
+			log_end_msg 1
+			;;
+		esac
 		;;
-
- 
-          *)
-                echo "Usage: $0 {start|stop|reload|force-reload|restart}" >&2
+        *)
+                log_success_msg "Usage: $0 {start|stop|status|reload|force-reload|restart}" >&2
 	        exit 1
 	esac
 	;;
